include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print: false
    - prefer_const_constructors: true
    - prefer_const_literals_to_create_immutables: true
    - unnecessary_this: true

analyzer:
  errors:
    # Suppress deprecated warnings untuk withOpacity (masih valid di Flutter 3.x)
    deprecated_member_use: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
